workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    triggering:
      events:
        - push
        - pull_request
      branches:
        include:
          - main
          - master

    environment:
      java: "17"
      vars:
        ANDROID_HOME: /opt/android-sdk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
