workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    triggering:
      events:
        - push
        - pull_request
      workflow: android-build   # required in new schema
      cancel_previous_builds: true
      auto:
        branch_patterns:
          - pattern: "main"
            include: true
            source: true
          - pattern: "master"
            include: true
            source: true

    environment:
      java: "17"
      vars:
        ANDROID_HOME: /opt/android-sdk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Make Gradle wrapper executable
        script: chmod +x ./gradlew

      - name: Clean
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

      - name: Build Release APK
        script: ./gradlew assembleRelease

      - name: Build Release AAB
        script: ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
